### ISSUE TITLE
[Tyrav1/2]mprove renderware´s diff and add txd support using aap´s library

### ISSUE THREAD

**Issue by Wolf3s** [h4570/tyra#103]
Well, i´m thinking to do a new upgrade on renderware files using a library developed by aap called librw 
follow the link here: https://github.com/aap/librw

**Comment by h4570** [comment]
I dropped `.dff` file support in Tyra 2.0.0.
Anyway it can be re-added in better way, waiting for contributors to step-in.

**Comment by Wolf3s** [comment]
> I dropped `.dff` file support in Tyra 2.0.0. Anyway it can be re-added in better way, waiting for contributors to step-in.

I should try to port some v1 formats to tyrav2
