### ISSUE TITLE
Create "Dolphin" sample

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#12]
Dolphin sample TO-DO (might be changed later)

- [ ] Animated water(mesh,code)
- [ ] Collectible (mesh,code)
- [ ] Seabed (mesh,code)
- [ ] Readme

**Comment by Foxar** [comment]
Dolphin sample:

Simple mini-game about swimming around as a dolphin, collecting collectibles by jumping and exploring, and avoiding threats. Possibly having multiple levels that switch upon enough collectibles being found.

**Comment by Foxar** [comment]
Updated the original post with a TO-DO.

**Comment by h4570** [comment]
Please dont forget about `readme.md` :)
