### ISSUE TITLE
Fix triangle clipping in drawByPath3()

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#13]
Currently drawByPath3() is generating some weird glitches, when mesh is partially outside of view frustum.
This is probably issue which should be in PS2SDK, but I will leave it there.

[Line in PS2SDK which propably cause the glitching](https://github.com/ps2dev/ps2sdk/blob/674b6f4b086fc2e98eadf4511d27d09365d36e3a/ee/math3d/src/math3d.c#L570)

Using in:
https://github.com/h4570/tyra/blob/d58163d75be2d6c848f4456f73cebd8a6c1a63bd/src/engine/modules/gif_sender.cpp#L217

**Comment by Foxar** [comment]
Visual example of the glitch:

![ixHKyrH0XG](https://user-images.githubusercontent.com/6164708/101185869-b2357c80-3652-11eb-942e-b20a117511a1.gif)

**Comment by h4570** [comment]
DrawByPath3() will be depreceated in next releases
