### ISSUE TITLE
Cross platform with x86 architecture

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#144]
I'm wondering about splitting strict PS2 code with shared (multiplatform) code.
This way, we can add automatical unit tests to shared code.

**Comment by Wolf3s** [comment]
> I'm wondering about splitting strict PS2 code with shared (multiplatform) code. This way, we can add automatical unit tests to shared code.

You mean this Engine will be multiplataform?

**Comment by h4570** [comment]
Hmm, only "partially".

I want to create 3 folders in `engine/src`:
```
engine/src/shared/
engine/src/x86/
engine/src/ps2/
```

And split existing code, so it will be **compilable** on windows/linux, but not **runnable**.
For example: `x86` implementation for renderer will be totally empty.

Of course it will open possibility to add easily real multiplatform in future, but I'm not planning it at this moment. 
I want to just add possibilty to run unit tests, and add a lot of unit tests.

**Comment by Wolf3s** [comment]
> 

Cool! I just recommend if you wanna do the Linux or other os, like instead of creating x86,  you could create `engine/src/pc/x86` or `engine/src/some os/some stuff/`
