### ISSUE TITLE
Soft reset is breaking PS2link connection.

### ISSUE THREAD

**Issue by Wellinator** [h4570/tyra#152]
https://github.com/h4570/tyra/blob/e3726600fd3a734af9066b2fa8db5131c8058122/engine/src/irx/irx_loader.cpp#L55

Do you remember why it was needed perform **SifIopReset** and **SifIopSync**?
The ps2link stop working when this code runs.
Using the "_Send to PS2_" task or manually using PS2link.

I've removed them and all the things kept working well, but need to be sure before PR.

**Comment by h4570** [comment]
To be honest I dont remember.
If tyra works correctly on ps2link, usb and pcsx2 without these lines, then they should be removed.

**Comment by Wellinator** [comment]
Okay. I'll investigate more carefully.

**Comment by Wolf3s** [comment]
Jun 4, 2023

> 

Update: removing this on real hardware causes crash.
