### ISSUE TITLE
Tutorials and demos not working on emulator and in real ps2

### ISSUE THREAD

**Issue by christianrss** [h4570/tyra#157]
Hi everyone,

I've been try to run the tutorials but the "elf" freezes in Tyra logo.

Has anyone had the same problem?

Thanks.

**Comment by Wolf3s** [comment]
> Hi everyone,
> 
> I've been try to run the tutorials but the "elf" freezes in Tyra logo.
> 
> Has anyone had the same problem?
> 
> Thanks.

I've had, but i'm working on it to find this bug , don't expect if this get fixed soon.

**Comment by h4570** [comment]
I dont have console at this moment, but emulator works fine

PCSX2 1.6.0
![image](https://github.com/h4570/tyra/assets/32263891/2dd6ec50-0780-451b-bc4f-9f13c887aec6)

PCSX2 1.7.4564 (with `Host file system enabled = true`)
![image](https://github.com/h4570/tyra/assets/32263891/3f33d63d-33cc-4810-8b12-281dba9b6c4a)

**Comment by wolfysdl** [comment]
> I dont have console at this moment, but emulator works fine

Correct it´s working on emulator maybe he has doesn´t enable the hostfs.

**Comment by Wolf3s** [comment]
> I dont have console at this moment, but emulator works fine
> 
> PCSX2 1.6.0 ![image](https://user-images.githubusercontent.com/32263891/244867348-2dd6ec50-0780-451b-bc4f-9f13c887aec6.png)
> 
> PCSX2 1.7.4564 (with `Host file system enabled = true`) ![image](https://user-images.githubusercontent.com/32263891/244867369-3f33d63d-33cc-4810-8b12-281dba9b6c4a.png)

Yes, it works but in Real hardware it really doesn't work

**Comment by GDQR** [comment]
I was testing the demo and the tutorials (except the first one) on a real PS2.

First I tried it with a 32GB pendrive that was not formatted and tutorial02 did not work, it got stuck on the Tyra logo. It seems that the problem was when opening a file from the pendrive and it gave me errno=12 (not enough space) and I had a lot of space, but I think those problems are because I did not format it. I will never be able to know, because I ended up breaking it XD. All this happened before I fixed the logfile in the debug.hpp.

Then I tried it with a 16GB pendrive, this time I formatted it and with the logfile fixed, I put the loadUsbDriver and they all worked for me.
The only problems I had was that in the demo I had a freeze for a moment using writeLogsToFile but without that I got along without problems.
In tutorial 4, the dust2 map some textures were loaded incorrectly.
In tutorial 6, the audio, the .wav was working poorly, the log gave me this:
==WARN: Channel is busy, please use another channel!

> > I dont have console at this moment, but emulator works fine
> > PCSX2 1.6.0 ![image](https://user-images.githubusercontent.com/32263891/244867348-2dd6ec50-0780-451b-bc4f-9f13c887aec6.png)
> > PCSX2 1.7.4564 (with `Host file system enabled = true`) ![image](https://user-images.githubusercontent.com/32263891/244867369-3f33d63d-33cc-4810-8b12-281dba9b6c4a.png)
> 
> Yes, it works but in Real hardware it really doesn't work

**Comment by Wolf3s** [comment]
> I was testing the demo and the tutorials (except the first one) on a real PS2.
> 
> First I tried it with a 32GB pendrive that was not formatted and tutorial02 did not work, it got stuck on the Tyra logo. It seems that the problem was when opening a file from the pendrive and it gave me errno=12 (not enough space) and I had a lot of space, but I think those problems are because I did not format it. I will never be able to know, because I ended up breaking it XD. All this happened before I fixed the logfile in the debug.hpp.
> 
> Then I tried it with a 16GB pendrive, this time I formatted it and with the logfile fixed, I put the loadUsbDriver and they all worked for me. The only problems I had was that in the demo I had a freeze for a moment using writeLogsToFile but without that I got along without problems. In tutorial 4, the dust2 map some textures were loaded incorrectly. In tutorial 6, the audio, the .wav was working poorly, the log gave me this: ==WARN: Channel is busy, please use another channel!
> 
> > > I dont have console at this moment, but emulator works fine
> > > PCSX2 1.6.0 ![image](https://user-images.githubusercontent.com/32263891/244867348-2dd6ec50-0780-451b-bc4f-9f13c887aec6.png)
> > > PCSX2 1.7.4564 (with `Host file system enabled = true`) ![image](https://user-images.githubusercontent.com/32263891/244867369-3f33d63d-33cc-4810-8b12-281dba9b6c4a.png)
> > 
> > 
> > Yes, it works but in Real hardware it really doesn't work

Maybe there are some bugs related to filesystem and modules

**Comment by Wolf3s** [comment]
I tried to solve this before, This problem is more deeper than i thinked at the time.

**Comment by GDQR** [comment]
> > I was testing the demo and the tutorials (except the first one) on a real PS2.
> > First I tried it with a 32GB pendrive that was not formatted and tutorial02 did not work, it got stuck on the Tyra logo. It seems that the problem was when opening a file from the pendrive and it gave me errno=12 (not enough space) and I had a lot of space, but I think those problems are because I did not format it. I will never be able to know, because I ended up breaking it XD. All this happened before I fixed the logfile in the debug.hpp.
> > Then I tried it with a 16GB pendrive, this time I formatted it and with the logfile fixed, I put the loadUsbDriver and they all worked for me. The only problems I had was that in the demo I had a freeze for a moment using writeLogsToFile but without that I got along without problems. In tutorial 4, the dust2 map some textures were loaded incorrectly. In tutorial 6, the audio, the .wav was working poorly, the log gave me this: ==WARN: Channel is busy, please use another channel!
> > > > I dont have console at this moment, but emulator works fine
> > > > PCSX2 1.6.0 ![image](https://user-images.githubusercontent.com/32263891/244867348-2dd6ec50-0780-451b-bc4f-9f13c887aec6.png)
> > > > PCSX2 1.7.4564 (with `Host file system enabled = true`) ![image](https://user-images.githubusercontent.com/32263891/244867369-3f33d63d-33cc-4810-8b12-281dba9b6c4a.png)
> > > 
> > > 
> > > Yes, it works but in Real hardware it really doesn't work
> 
> Maybe there are some bugs related to filesystem and modules

To clarify with tutorial 4, the textures are loaded but some appear stretched

**Comment by Wolf3s** [comment]
> > > I was testing the demo and the tutorials (except the first one) on a real PS2.
> > > First I tried it with a 32GB pendrive that was not formatted and tutorial02 did not work, it got stuck on the Tyra logo. It seems that the problem was when opening a file from the pendrive and it gave me errno=12 (not enough space) and I had a lot of space, but I think those problems are because I did not format it. I will never be able to know, because I ended up breaking it XD. All this happened before I fixed the logfile in the debug.hpp.
> > > Then I tried it with a 16GB pendrive, this time I formatted it and with the logfile fixed, I put the loadUsbDriver and they all worked for me. The only problems I had was that in the demo I had a freeze for a moment using writeLogsToFile but without that I got along without problems. In tutorial 4, the dust2 map some textures were loaded incorrectly. In tutorial 6, the audio, the .wav was working poorly, the log gave me this: ==WARN: Channel is busy, please use another channel!
> > > > > I dont have console at this moment, but emulator works fine
> > > > > PCSX2 1.6.0 ![image](https://user-images.githubusercontent.com/32263891/244867348-2dd6ec50-0780-451b-bc4f-9f13c887aec6.png)
> > > > > PCSX2 1.7.4564 (with `Host file system enabled = true`) ![image](https://user-images.githubusercontent.com/32263891/244867369-3f33d63d-33cc-4810-8b12-281dba9b6c4a.png)
> > > > 
> > > > 
> > > > Yes, it works but in Real hardware it really doesn't work
> > 
> > 
> > Maybe there are some bugs related to filesystem and modules
> 
> To clarify with tutorial 4, the textures are loaded but some appear stretched

So it should be a minnor bug at math section or something

**Comment by h4570** [comment]
Closing, cause emulator is working fine on PCSX2 1.6 and PCSX2 1.7.
When it comes to real hardware, I will create separate issue for this
