### ISSUE TITLE
Change AABB (bounding box) from array to struct

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#16]
@Foxar please describe the plan if you could.

https://github.com/h4570/tyra/blob/d58163d75be2d6c848f4456f73cebd8a6c1a63bd/src/engine/include/models/mesh_frame.hpp#L142

**Comment by Foxar** [comment]
I imagine creating a struct for the boundingbox, which would hold in it the 8 vectors that describe the corners of the boundingbox.
It'd allow for methods such as

- getHeight()
- getWidth()
- getLength()(?)
- getTop() (Y coordinate of the highest vector)
- getBottom() (Analogous to above)

And more.
