### ISSUE TITLE
Add 2D font support

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#17]
There are two ways of doing this.

1. Use [PS2SDK font library](https://github.com/ps2dev/ps2sdk/blob/674b6f4b086fc2e98eadf4511d27d09365d36e3a/ee/font/samples/font.c#L166), but this will require for us impress.ini file which is not present in PS2SDK.

2. Better option - do it similiar like in [gsKit](https://github.com/ps2dev/gsKit/blob/e60f71764b35d88307511715f854a94b17b31db7/examples/font/font.c#L58), but this require more effort

**Comment by Wellinator** [comment]
I was studing the font sample from PS2SDK but coudn't run without that "impress.ini". Any idea what is this file?

**Comment by h4570** [comment]
Once, I also made an attempt to search for this file. In my opinion this file was somehow lost while porting the PS2SDK from Subversion to Git a long time ago. Unfortunately I think that the best option is to do it like in gsKit.

**Comment by h4570** [comment]
Still an issue in Tyra 2.0.0.

Im wondering about implementing of bmfont file support
 https://www.angelcode.com/products/bmfont/

**Comment by h4570** [comment]
Resolved couple of months ago
