### ISSUE TITLE
Animations rework

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#19]
@Foxar please describe the plan if you could.

- [ ] Add stopAnimation()
- [ ] Add isAnimating()
- [ ] Create array of animation structs. Like playAnimation("jump")

https://github.com/h4570/tyra/blob/d58163d75be2d6c848f4456f73cebd8a6c1a63bd/src/engine/include/models/mesh.hpp#L204

**Comment by Foxar** [comment]
At this moment there's nothing else I can think of regarding the animations, I'll add more If i think of them.

**Comment by h4570** [comment]
Reworked in Tyra 2.0.0
