### ISSUE TITLE
Repo description

### ISSUE THREAD

**Issue by Foxar** [h4570/tyra#31]
I don't quite think labeling tyra as a "renderer" does it justice. It manages model loading, sound playing, I/O for the controllers and we plan to add more, with renderer being only a part of it. @h4570 

I suggest we change the description to not incude the 'renderer' part as it implies it's only that. "Game engine" or "Multimedia library" or such would be more accurate.

**Comment by h4570** [comment]
To be honest, I want to use the word engine, but I was a little scared of it. Because Tyra was not ready for it :D
I think with the next update, we can change it back to the game engine.

**Comment by Foxar** [comment]
It already is an engine, it processes player input for instance. Plus even if it's 'not ready yet', well the project is in-development is it not, we're describing what it's meant to be not what it is right now, in my opinion any way.
Either way, this issue can be closed or resolved with a desc edit

**Comment by h4570** [comment]
I think that I will work a little with `readme.md`. I'm adding this issue to the **December release** project.
