### ISSUE TITLE
Include deltatime-based behavior in engine classes

### ISSUE THREAD

**Issue by Foxar** [h4570/tyra#48]
Currently, the games built with Tyra need to manage the delta-time usage themselves. This means moving an object by speed * 60/currentFPS, to achieve a FPS-independent movement. I had an idea to introduce methods to classes like mesh.cpp whereby changes to their member variables would automatically be influenced by deltatime. Such as mesh::moveByDeltaTime(Vector3);

The plus side is it'd make it easier to create game with Tyra, having automated that process. The minus is it might be considered bloat and unnecessary as developers might have different ideas in mind for how to handle their physics and ignore such methods entirely.

I need your opinion, @h4570

**Comment by Foxar** [comment]
I sorta don't like this idea anymore, as every possible action that needs to be mulitplier/divided by the deltatime would need it's own version of such a method, which is very redundant.

**Comment by h4570** [comment]
Resolved in Tyra 2.0.0
