### ISSUE TITLE
Add multiple track mixing for audio

### ISSUE THREAD

**Issue by Foxar** [h4570/tyra#51]
To allow multiple songs to be played (for instance, soundtrack and an ambient).

**Comment by h4570** [comment]
Hmm. It can be done right now via playing multiple adpcm samples (`playADPCM()`).
When it comes to `playSong()` (the background one), current PS2SDK library does not have this feature. 
I think this is issue more to PS2SDK than the Tyra, but we can keep it there, just to remember.
