### ISSUE TITLE
Add stopAudio() to audio class.

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#53]
Current problem is that, we cant really stop the ADPCM sample.
I wonder, that we can add wrapper to `audsrv_stop_audio()` in our audio class.
We need some check how this function works, and how we can use it in audio class.

**Comment by Foxar** [comment]
Just a comment, FYI, what I managed to do in Dolphin sample does not 'solve' in any way this issue, as it's just a workaround (and a clumsy one too). I think this issue should persist.

**Comment by h4570** [comment]
Also there is idea to create Audio class 2.0, where user will NOT specify channel, and class will be automatically adjusting volume and use right ADPCM channel.
