### ISSUE TITLE
Allow arguments of volume and pitch to be used for ADPCM player.

### ISSUE THREAD

**Issue by Foxar** [h4570/tyra#55]
Right now, if I want a sound to play at a specific volume, I have to go the long winded way of doing:

`audio.setADPCMVolume(40, 2);`
`audio.playADPCM(sound, 2);`

This also means the channel 2 will stay at volume 40, forcing the user to either: 

- Always set the volume they desire for the sound effect or
- Creating some timer-based channel volume resets to 100. 

I think either enabling the user to designate the volume (and pitch maybe) while using playADPCM() could simplify the first option, while also the timed mechanism i spoke of can also be introduced to Tyra.

I believe it's a good idea as Tyra's meant to be a simple way to make PS2 games, and such an automatic volume reset (opt2) / consolidation of parameter setting (opt1) may simplify the process.

**Comment by h4570** [comment]
Not resolved in Tyra 2.0.0.
Its more a PS2SDK -> audsrv issue
