### ISSUE TITLE
Add "starter" sample

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#57]
I think that there will be good idea to add "starter" sample, which should be an easy start with Tyra.

**Comment by Foxar** [comment]
Can you go into detail ?

**Comment by h4570** [comment]
My idea is to create simple "hello world" sample with 3D and 2D object.
For example rotating cube with 2D random picture.

**Comment by Wellinator** [comment]
I had a similar idea about the cube, I'll go for it then.

**Comment by Wellinator** [comment]
Almost finished, I guess I'll put tyra art in the cube texture. IN PROGRESS

**Comment by h4570** [comment]
Great to hear it!
