### ISSUE TITLE
PRINT_ERR String formatting

### ISSUE THREAD

**Issue by Foxar** [h4570/tyra#64]
If we'd allow for syntax similar to printf and feeding variable values into PRINT_ERR it could allow for more informative error messages 
Example:
`PRINT_ERR("Failed to load file %s!\n",someString)`

**Comment by h4570** [comment]
I think that this one can be merged with https://github.com/h4570/tyra/issues/23

**Comment by Foxar** [comment]
Oh yeah, agreed.
