### ISSUE TITLE
Enable rendering of meshes without textures / normals data.

### ISSUE THREAD

**Issue by Foxar** [h4570/tyra#66]
Currently the renderer, as far as I'm aware is not capable of rendering texture or normals data. It'd be beneficient to allow such, limiting crashing and allowing to test models within Tyra without having to provide full set of data for them.

**Comment by h4570** [comment]
I've added non textured rendering feature.
I think that we should grab color information from .obj file also.
At this moment, colors must be set manually.

**Comment by Foxar** [comment]
I'd like to suggest hardcoded color of some kind to be set, unless .obj file specifies a different kind of color, so that the model always has a some kind of color to rely on, allowing the model to be seen (and also to see if it's rendering properly)

**Comment by h4570** [comment]
Resolved in Tyra 2.0.0
