### ISSUE TITLE
Dolphin: Deep diving causes a game freeze

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#78]
When you will deep dive on dolphin sample, game will freeze.
Can be reproduced on PCSX2 and PS2

**Comment by Foxar** [comment]
I've tracked the issue down to 
`engine->renderer->draw(waterDrawList, WATER_TILES_COUNT);`
call, which seems to be the source of the crash. It seems to be that passing a Mesh array and size of it to the renderer causes the issue. I'll instead try to iterate through the mesh array and render them one at a time. It does not solve the issue, which may lie in the renderer function itself.

**Comment by Foxar** [comment]
I noticed also that the crash occured when the water surface models were almost completely invisible, which could indicate that asking the renderer to draw an array of meshes that are not in camera view at the time is the reason behind the crashing.

**Comment by h4570** [comment]
Thank you for this investigation and workaround implementation.
Issue is still open, and I will try to check this out in free time

**Comment by Foxar** [comment]
I unassigned myself as the issue seems to be deep within renderer's functionality, which I rather not mess around with, as I understand @h4570 will get around to it soon.

**Comment by h4570** [comment]
Resolved in Tyra 2.0.0
