### ISSUE TITLE
Dolphin: Fast collecting oysters cause ADPCM crash

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#79]
When you will try to collect oysters quickly, there is big chance to get `ADPCM channel used` error.
  
![image](https://user-images.githubusercontent.com/32263891/103177533-af0d6500-487b-11eb-8a26-353685201734.png)

**Comment by Foxar** [comment]
I can't seem to be able to reproduce this bug. Even when trying to play sounds over and over by ramming the mines it doesn't happen. I'm aware that playing sounds over each other can cause a crash, but I remember balancing the game in such a way that this isn't quite possible. Could you be more specific on how you make this crash happen?

(Perhaps an update to ps2dev has fixed the sound overlapping crashing?)

**Comment by h4570** [comment]
I need to double check that.
If I fail to reproduce this bug, I will close that issue.
